/******************************************************************* 
 * C file generated by Protoc for Embedded C.                      *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : data.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/
 
#include "Data.h"

int _memcmp(const void *p1, const void *p2, unsigned int size) {
    unsigned int i;
    for(i = 0; i < size; ++ i) {
        if(*((char*)p1 + i) > *((char*)p2 + i))
            return 1;
        if(*((char*)p1 + i) < *((char*)p2 + i))
            return -1;
    }
    return 0;
} 
 
void _memset(void *msg_ptr, char init_val, unsigned int size) {
    unsigned int i;
    for(i = 0; i < size; ++ i)
        *((char*)msg_ptr + i) = init_val;
}

int varint_packed_size(unsigned long value) {
    if ((value & (0xffffffff <<  7)) == 0) return 1;
    if ((value & (0xffffffff << 14)) == 0) return 2;
    if ((value & (0xffffffff << 21)) == 0) return 3;
    if ((value & (0xffffffff << 28)) == 0) return 4;
    return 5;  
}

int write_raw_byte(char value, void *_buffer, int offset) {
    *((char *)_buffer + offset) = value;
    return ++offset;
}

/** Write a little-endian 32-bit integer. */
int write_raw_little_endian32(unsigned long value, void *_buffer, int offset) {
    offset = write_raw_byte((char)((value      ) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >>  8) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 16) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 24) & 0xFF), _buffer, offset);
    
    return offset;
}

/** Write a little-endian 64-bit integer. */
int write_raw_little_endian64(unsigned long long value, void *_buffer, int offset) {
    offset = write_raw_byte((char)((value      ) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >>  8) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 16) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 24) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 32) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 40) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 48) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 56) & 0xFF), _buffer, offset);
    
    return offset;
}

int write_raw_varint32(unsigned long value, void *_buffer, int offset) {
    while (1) {
        if ((value & ~0x7F) == 0) {
            offset = write_raw_byte((char)value, _buffer, offset);
            return offset;
        } else {
            offset = write_raw_byte((char)((value & 0x7F) | 0x80), _buffer, offset);
            value = value >> 7;
        }
    }
    return offset;
}

int write_raw_varint64(unsigned long long value, void *_buffer, int offset) {
    while (1) {
        if ((value & ~0x7FL) == 0) {
            offset = write_raw_byte((char)value, _buffer, offset);
            return offset;
        } else {
            offset = write_raw_byte((char)((value & 0x7F) | 0x80), _buffer, offset);
            value = value >> 7;
        }
    }
    return offset;
}

int write_raw_bytes(char *bytes, int bytes_size, void *_buffer, int offset) {
    int i; 
    for(i = 0; i < bytes_size; ++ i) {
        offset = write_raw_byte((char)*(bytes + i), _buffer, offset);
    }
    
    return offset;   
}

unsigned long encode_zig_zag32(signed long n) {
    /* Note:  the right-shift must be arithmetic. */
    return (n << 1) ^ (n >> 31);
}

unsigned long long encode_zig_zag64(signed long long n) {
    /* Note:  the right-shift must be arithmetic. */
    return (n << 1) ^ (n >> 63);
} 

signed long decode_zig_zag32(unsigned long n) {
    return (n >> 1) ^ -(n & 1);
}

signed long long decode_zig_zag64(unsigned long long n) {
    return (n >> 1) ^ -(n & 1);
}

int read_raw_byte(char *tag, void *_buffer, int offset) {
    *tag = *((char *) _buffer + offset);
    
    return ++offset;
}

/** Read a 32-bit little-endian integer from the stream. */
int read_raw_little_endian32(unsigned long *tag, void *_buffer, int offset) {
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b1 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b2 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b3 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b4 = (char) *tag;
    
    *tag = (((unsigned long)b1 & 0xff)      ) |
           (((unsigned long)b2 & 0xff) <<  8) |
           (((unsigned long)b3 & 0xff) << 16) |
           (((unsigned long)b4 & 0xff) << 24);
           
    return offset;
}

/** Read a 64-bit little-endian integer from the stream. */
int read_raw_little_endian64(unsigned long long *tag, void *_buffer, int offset) {
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b1 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b2 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b3 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b4 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b5 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b6 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b7 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b8 = (char) *tag;
    
    *tag = (((unsigned long long)b1 & 0xff)      ) |
           (((unsigned long long)b2 & 0xff) <<  8) |
           (((unsigned long long)b3 & 0xff) << 16) |
           (((unsigned long long)b4 & 0xff) << 24) |
           (((unsigned long long)b5 & 0xff) << 32) |
           (((unsigned long long)b6 & 0xff) << 40) |
           (((unsigned long long)b7 & 0xff) << 48) |
           (((unsigned long long)b8 & 0xff) << 56);
           
    return offset;
}

int read_raw_varint32(unsigned long *tag, void *_buffer, int offset) {
    signed char result;
    
    offset = read_raw_byte((char *)&result, _buffer, offset);
    if (result >= 0) {
        *tag = result;
        return offset;
    }
    *tag = result & 0x7f;
    offset = read_raw_byte((char *)&result, _buffer, offset);
    if (result >= 0) {
        *tag |= result << 7;
    } else {
        *tag |= (result & 0x7f) << 7;
        offset = read_raw_byte((char *)&result, _buffer, offset);
        if (result >= 0) {
            *tag |= result << 14;
        } else {
            *tag |= (result & 0x7f) << 14;
            offset = read_raw_byte((char *)&result, _buffer, offset);
            if (result >= 0) {
                *tag |= ((unsigned long)result) << 21;
            } else {
                *tag |= (((unsigned long)result) & 0x7f) << 21;
                offset = read_raw_byte((char *)&result, _buffer, offset);
                *tag |= ((unsigned long)result) << 28;
                if (result < 0) {
                    /* Discard upper 32 bits. */
                    int i;
                    for (i = 0; i < 5; ++ i) {
                        offset = read_raw_byte((char *)&result, _buffer, offset);
                        if (result >= 0) {
                            return offset;
                        }
                    }
                    /* Invalid state. */
                }
            }
        }
    }
    return offset;
}

int read_raw_varint64(unsigned long long *tag, void *_buffer, int offset) {
    short shift = 0;
    signed char b;
    *tag = 0;
    while (shift < 64) {
        offset = read_raw_byte((char *)&b, _buffer, offset);
        *tag |= (unsigned long long)(b & 0x7F) << shift;
        if ((b & 0x80) == 0) {
            return offset;
        }
        shift += 7;
    }
    /* return error code. */
    return -1;
}

int can_read_raw_varint32(void *_buffer, int offset, int length) {
    signed char c;
    
    /* Bound length to valid range [0..5]. */
    if (length < 0) length = 0; else
    if (length > 5) length = 5;
    
    while (length > 0) {
        offset = read_raw_byte((char *)&c, _buffer, offset);
        if (c >= 0) {
            return 1; /* Can read (1 == true). */
        }
        length--;
    }
    
    return 0; /* Cannot read (0 == false). */
}

int can_read_raw_varint64(void *_buffer, int offset, int length) {
    signed char c;
    
    /* Bound length to valid range [0..5]. */
    if (length < 0) length = 0; else
    if (length > 10) length = 10;
    
    while (length > 0) {
        offset = read_raw_byte((char *)&c, _buffer, offset);
        if (c >= 0) {
            return 1; /* Can read (1 == true). */
        }
        length--;
    }
    
    return 0; /* Cannot read (0 == false). */
}

int Message_can_read_delimited_from(void *_buffer, int offset, unsigned int length) {
    unsigned long size;
    int payload_offset;

    if (length <= 0) return 0; /* Cannot read from empty or invalid message. */

    if (!can_read_raw_varint32(_buffer, offset, length)) {
        return 0; /* Could not even read the preceding size as varint32. */
    }

    payload_offset = read_raw_varint32(&size, _buffer, offset);
    length = length - (payload_offset - offset);

    return (length >= size) ? 1 : 0;
}

unsigned long Message_get_delimited_size(void *_buffer, int offset) {
    unsigned long size = 0;
    int old_offset = offset;
    
    offset = read_raw_varint32(&size, _buffer, offset);
    
    return size + offset - old_offset;
}

/*******************************************************************
* Enumeration: Data.proto, line 10
*******************************************************************/
int vb_data_type_t_write_with_tag(enum vb_data_type_t *_vb_data_type_t, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+0, _buffer, offset);
    /* Write content.*/
    offset = write_raw_varint32(*_vb_data_type_t, _buffer, offset);
    
    return offset;
}


/*******************************************************************
 * Message: Data.proto, line 17
 *******************************************************************/

void Data_clear(struct Data *_Data) {
	_memset(_Data, 0, sizeof(struct Data));
}

void Data_init_optional_attributes(struct Data *_Data) {
	_Data->_handle = 0;
	
	_Data->_data_int = 0;
	
	_Data->_data_float = 0.0f;
	
	_Data->_data_float_x = 0.0f;
	
	_Data->_data_float_y = 0.0f;
	
	_Data->_data_float_z = 0.0f;
	
}

int Data_is_default_message(struct Data *_Data) {
    return _Data->_handle == 0
    
     && _Data->_data_int == 0
    
     && _Data->_data_float == 0.0f
    
     && _Data->_data_float_x == 0.0f
    
     && _Data->_data_float_y == 0.0f
    
     && _Data->_data_float_z == 0.0f
    ;
}

int Data_write(struct Data *_Data, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_Data->_handle != 0) {
		offset = write_raw_varint32((1<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_Data->_handle, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_Data->_data_int != 0) {
		offset = write_raw_varint32((3<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_Data->_data_int, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_Data->_data_float != 0) {
		offset = write_raw_varint32((4<<3)+5, _buffer, offset);
	    unsigned long *data_float_ptr = (unsigned long *)&_Data->_data_float;
	    offset = write_raw_little_endian32(*data_float_ptr, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_Data->_data_float_x != 0) {
		offset = write_raw_varint32((5<<3)+5, _buffer, offset);
	    unsigned long *data_float_x_ptr = (unsigned long *)&_Data->_data_float_x;
	    offset = write_raw_little_endian32(*data_float_x_ptr, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_Data->_data_float_y != 0) {
		offset = write_raw_varint32((6<<3)+5, _buffer, offset);
	    unsigned long *data_float_y_ptr = (unsigned long *)&_Data->_data_float_y;
	    offset = write_raw_little_endian32(*data_float_y_ptr, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_Data->_data_float_z != 0) {
		offset = write_raw_varint32((7<<3)+5, _buffer, offset);
	    unsigned long *data_float_z_ptr = (unsigned long *)&_Data->_data_float_z;
	    offset = write_raw_little_endian32(*data_float_z_ptr, _buffer, offset);
	}
	
	return offset;
}

int Data_write_with_tag(struct Data *_Data, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = Data_write_delimited_to(_Data, _buffer, offset);
	
	return offset;
}

int Data_write_delimited_to(struct Data *_Data, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = Data_write(_Data, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int Data_read(void *_buffer, struct Data *_Data, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	Data_clear(_Data);
	/* Assign the optional attributes. */
	Data_init_optional_attributes(_Data);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _Data._handle */
	        case 1 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Data->_handle = tag;
	        	break;
	        /* tag of: _Data._data_int */
	        case 3 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_Data->_data_int = tag;
	        	break;
	        /* tag of: _Data._data_float */
	        case 4 :
	        	offset = read_raw_little_endian32(&tag, _buffer, offset);
	        	float *data_float = (float *)(&tag);
	        	_Data->_data_float = *data_float;
	        	break;
	        /* tag of: _Data._data_float_x */
	        case 5 :
	        	offset = read_raw_little_endian32(&tag, _buffer, offset);
	        	float *data_float_x = (float *)(&tag);
	        	_Data->_data_float_x = *data_float_x;
	        	break;
	        /* tag of: _Data._data_float_y */
	        case 6 :
	        	offset = read_raw_little_endian32(&tag, _buffer, offset);
	        	float *data_float_y = (float *)(&tag);
	        	_Data->_data_float_y = *data_float_y;
	        	break;
	        /* tag of: _Data._data_float_z */
	        case 7 :
	        	offset = read_raw_little_endian32(&tag, _buffer, offset);
	        	float *data_float_z = (float *)(&tag);
	        	_Data->_data_float_z = *data_float_z;
	        	break;
	    }
	}
	
	return offset;
}

int Data_read_delimited_from(void *_buffer, struct Data *_Data, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	Data_read(_buffer, _Data, offset, size + offset);
	
	return offset + size;
}
/*******************************************************************
 * Message: Data.proto, line 26
 *******************************************************************/

void DataDescription_clear(struct DataDescription *_DataDescription) {
	_memset(_DataDescription, 0, sizeof(struct DataDescription));
}

void DataDescription_init_optional_attributes(struct DataDescription *_DataDescription) {
	_DataDescription->_field_name_len = 0;
	
	
	_DataDescription->_type = 0;
	
	_DataDescription->_handle = 0;
	
}

int DataDescription_is_default_message(struct DataDescription *_DataDescription) {
    return _DataDescription->_field_name_len == 0
    
     && _DataDescription->_type == 0
    
     && _DataDescription->_handle == 0
    ;
}

int DataDescription_write(struct DataDescription *_DataDescription, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(_DataDescription->_field_name_len != 1
	    || _DataDescription->_field_name[0] != '0') {
		offset = write_raw_varint32((1<<3)+2, _buffer, offset);
	    offset = write_raw_varint32(_DataDescription->_field_name_len, _buffer, offset);
	    offset = write_raw_bytes(_DataDescription->_field_name, _DataDescription->_field_name_len, _buffer, offset);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_DataDescription->_type != 0) {
	    offset = vb_data_type_t_write_with_tag(&_DataDescription->_type, _buffer, offset, 2);
	}
	
	/* Write the optional attribute only if it is different than the default value. */
	if(_DataDescription->_handle != 0) {
		offset = write_raw_varint32((3<<3)+0, _buffer, offset);
	    offset = write_raw_varint32(_DataDescription->_handle, _buffer, offset);
	}
	
	return offset;
}

int DataDescription_write_with_tag(struct DataDescription *_DataDescription, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = DataDescription_write_delimited_to(_DataDescription, _buffer, offset);
	
	return offset;
}

int DataDescription_write_delimited_to(struct DataDescription *_DataDescription, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = DataDescription_write(_DataDescription, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int DataDescription_read(void *_buffer, struct DataDescription *_DataDescription, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	DataDescription_clear(_DataDescription);
	/* Assign the optional attributes. */
	DataDescription_init_optional_attributes(_DataDescription);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _DataDescription._field_name */
	        case 1 :
	        	/* Re-use 'tag' to store string length. */
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_DataDescription->_field_name_len = tag;
	        	for(i = 0; i < tag; ++ i) 
	        	    offset = read_raw_byte((_DataDescription->_field_name + i), _buffer, offset);
	        	break;
	        /* tag of: _DataDescription._type */
	        case 2 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_DataDescription->_type = tag;
	        	break;
	        /* tag of: _DataDescription._handle */
	        case 3 :
	        	offset = read_raw_varint32(&tag, _buffer, offset);
	        	_DataDescription->_handle = tag;
	        	break;
	    }
	}
	
	return offset;
}

int DataDescription_read_delimited_from(void *_buffer, struct DataDescription *_DataDescription, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	DataDescription_read(_buffer, _DataDescription, offset, size + offset);
	
	return offset + size;
}
/*******************************************************************
 * Message: Data.proto, line 32
 *******************************************************************/

void Packet_clear(struct Packet *_Packet) {
	_memset(_Packet, 0, sizeof(struct Packet));
}

void Packet_init_optional_attributes(struct Packet *_Packet) {
	Data_init_optional_attributes(&_Packet->_data);
	
}

int Packet_is_default_message(struct Packet *_Packet) {
    return Data_is_default_message(&_Packet->_data)
    
     && 
}

int Packet_write(struct Packet *_Packet, void *_buffer, int offset) {
	/* Write content of each message element.*/
	/* Write the optional attribute only if it is different than the default value. */
	if(!Data_is_default_message(&_Packet->_data)) {
	    offset = Data_write_with_tag(&_Packet->_data, _buffer, offset, 1);
	}
	
	int data_descriptions_cnt;
	for (data_descriptions_cnt = 0; data_descriptions_cnt < _Packet->_data_descriptions_repeated_len; ++ data_descriptions_cnt) {
	    offset = DataDescription_write_with_tag(&_Packet->_data_descriptions[data_descriptions_cnt], _buffer, offset, 2);
	}
	
	return offset;
}

int Packet_write_with_tag(struct Packet *_Packet, void *_buffer, int offset, int tag) {
	/* Write tag.*/
	offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
	/* Write content.*/
	offset = Packet_write_delimited_to(_Packet, _buffer, offset);
	
	return offset;
}

int Packet_write_delimited_to(struct Packet *_Packet, void *_buffer, int offset) {
	int i, shift, new_offset, size;
	
	new_offset = Packet_write(_Packet, _buffer, offset);
	size = new_offset - offset;
	shift = (size > 127) ? 2 : 1;
	for (i = new_offset - 1; i >= offset; -- i)
	    *((char *)_buffer + i + shift) = *((char *)_buffer + i);
	
	write_raw_varint32((unsigned long) size, _buffer, offset);         
	    
	return new_offset + shift;
}

int Packet_read(void *_buffer, struct Packet *_Packet, int offset, int limit) {
	unsigned int i = 0;
	unsigned long long value = i;
	unsigned long tag = value;
	
	/* Reset all attributes to 0 in advance. */
	Packet_clear(_Packet);
	/* Assign the optional attributes. */
	Packet_init_optional_attributes(_Packet);
	
	/* Read/interpret all attributes from buffer offset until upper limit is reached. */
	while(offset < limit) {
	    offset = read_raw_varint32(&tag, _buffer, offset);
		tag = tag>>3;
	    switch(tag){
	        /* tag of: _Packet._data */
	        case 1 :
	        	offset = Data_read_delimited_from(_buffer, &_Packet->_data, offset);
	        	break;
	        /* tag of: _Packet._data_descriptions */
	        case 2 :
	        	offset = DataDescription_read_delimited_from(_buffer, &_Packet->_data_descriptions[(int)_Packet->_data_descriptions_repeated_len++], offset);
	        	break;
	    }
	}
	
	return offset;
}

int Packet_read_delimited_from(void *_buffer, struct Packet *_Packet, int offset) {
	unsigned long size;
	
	offset = read_raw_varint32(&size, _buffer, offset);
	Packet_read(_buffer, _Packet, offset, size + offset);
	
	return offset + size;
}
