// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/data.proto

#ifndef PROTOBUF_protobuf_2fdata_2eproto__INCLUDED
#define PROTOBUF_protobuf_2fdata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protobuf_2fdata_2eproto();
void protobuf_AssignDesc_protobuf_2fdata_2eproto();
void protobuf_ShutdownFile_protobuf_2fdata_2eproto();

class Data;
class DataRegistration;
class DataLabel;
class Packet;

enum vb_data_type_t {
  VB_DATATYPE_NONE = 0,
  VB_DATATYPE_INT = 1,
  VB_DATATYPE_FLOAT = 2,
  VB_DATATYPE_VECTOR = 3
};
bool vb_data_type_t_IsValid(int value);
const vb_data_type_t vb_data_type_t_MIN = VB_DATATYPE_NONE;
const vb_data_type_t vb_data_type_t_MAX = VB_DATATYPE_VECTOR;
const int vb_data_type_t_ARRAYSIZE = vb_data_type_t_MAX + 1;

const ::google::protobuf::EnumDescriptor* vb_data_type_t_descriptor();
inline const ::std::string& vb_data_type_t_Name(vb_data_type_t value) {
  return ::google::protobuf::internal::NameOfEnum(
    vb_data_type_t_descriptor(), value);
}
inline bool vb_data_type_t_Parse(
    const ::std::string& name, vb_data_type_t* value) {
  return ::google::protobuf::internal::ParseNamedEnum<vb_data_type_t>(
    vb_data_type_t_descriptor(), name, value);
}
// ===================================================================

class Data : public ::google::protobuf::Message {
 public:
  Data();
  virtual ~Data();

  Data(const Data& from);

  inline Data& operator=(const Data& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Data& default_instance();

  void Swap(Data* other);

  // implements Message ----------------------------------------------

  Data* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Data& from);
  void MergeFrom(const Data& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 handle = 1;
  inline bool has_handle() const;
  inline void clear_handle();
  static const int kHandleFieldNumber = 1;
  inline ::google::protobuf::uint32 handle() const;
  inline void set_handle(::google::protobuf::uint32 value);

  // optional uint32 data_int = 3;
  inline bool has_data_int() const;
  inline void clear_data_int();
  static const int kDataIntFieldNumber = 3;
  inline ::google::protobuf::uint32 data_int() const;
  inline void set_data_int(::google::protobuf::uint32 value);

  // optional float data_float = 4;
  inline bool has_data_float() const;
  inline void clear_data_float();
  static const int kDataFloatFieldNumber = 4;
  inline float data_float() const;
  inline void set_data_float(float value);

  // optional float data_float_x = 5;
  inline bool has_data_float_x() const;
  inline void clear_data_float_x();
  static const int kDataFloatXFieldNumber = 5;
  inline float data_float_x() const;
  inline void set_data_float_x(float value);

  // optional float data_float_y = 6;
  inline bool has_data_float_y() const;
  inline void clear_data_float_y();
  static const int kDataFloatYFieldNumber = 6;
  inline float data_float_y() const;
  inline void set_data_float_y(float value);

  // optional float data_float_z = 7;
  inline bool has_data_float_z() const;
  inline void clear_data_float_z();
  static const int kDataFloatZFieldNumber = 7;
  inline float data_float_z() const;
  inline void set_data_float_z(float value);

  // optional double time = 8;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 8;
  inline double time() const;
  inline void set_time(double value);

  // @@protoc_insertion_point(class_scope:Data)
 private:
  inline void set_has_handle();
  inline void clear_has_handle();
  inline void set_has_data_int();
  inline void clear_has_data_int();
  inline void set_has_data_float();
  inline void clear_has_data_float();
  inline void set_has_data_float_x();
  inline void clear_has_data_float_x();
  inline void set_has_data_float_y();
  inline void clear_has_data_float_y();
  inline void set_has_data_float_z();
  inline void clear_has_data_float_z();
  inline void set_has_time();
  inline void clear_has_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 handle_;
  ::google::protobuf::uint32 data_int_;
  float data_float_;
  float data_float_x_;
  float data_float_y_;
  float data_float_z_;
  double time_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_protobuf_2fdata_2eproto();
  friend void protobuf_AssignDesc_protobuf_2fdata_2eproto();
  friend void protobuf_ShutdownFile_protobuf_2fdata_2eproto();

  void InitAsDefaultInstance();
  static Data* default_instance_;
};
// -------------------------------------------------------------------

class DataRegistration : public ::google::protobuf::Message {
 public:
  DataRegistration();
  virtual ~DataRegistration();

  DataRegistration(const DataRegistration& from);

  inline DataRegistration& operator=(const DataRegistration& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DataRegistration& default_instance();

  void Swap(DataRegistration* other);

  // implements Message ----------------------------------------------

  DataRegistration* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DataRegistration& from);
  void MergeFrom(const DataRegistration& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string field_name = 1;
  inline bool has_field_name() const;
  inline void clear_field_name();
  static const int kFieldNameFieldNumber = 1;
  inline const ::std::string& field_name() const;
  inline void set_field_name(const ::std::string& value);
  inline void set_field_name(const char* value);
  inline void set_field_name(const char* value, size_t size);
  inline ::std::string* mutable_field_name();
  inline ::std::string* release_field_name();
  inline void set_allocated_field_name(::std::string* field_name);

  // optional .vb_data_type_t type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::vb_data_type_t type() const;
  inline void set_type(::vb_data_type_t value);

  // optional uint32 handle = 3;
  inline bool has_handle() const;
  inline void clear_handle();
  static const int kHandleFieldNumber = 3;
  inline ::google::protobuf::uint32 handle() const;
  inline void set_handle(::google::protobuf::uint32 value);

  // optional float range_min = 4;
  inline bool has_range_min() const;
  inline void clear_range_min();
  static const int kRangeMinFieldNumber = 4;
  inline float range_min() const;
  inline void set_range_min(float value);

  // optional float range_max = 5;
  inline bool has_range_max() const;
  inline void clear_range_max();
  static const int kRangeMaxFieldNumber = 5;
  inline float range_max() const;
  inline void set_range_max(float value);

  // @@protoc_insertion_point(class_scope:DataRegistration)
 private:
  inline void set_has_field_name();
  inline void clear_has_field_name();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_handle();
  inline void clear_has_handle();
  inline void set_has_range_min();
  inline void clear_has_range_min();
  inline void set_has_range_max();
  inline void clear_has_range_max();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* field_name_;
  int type_;
  ::google::protobuf::uint32 handle_;
  float range_min_;
  float range_max_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_protobuf_2fdata_2eproto();
  friend void protobuf_AssignDesc_protobuf_2fdata_2eproto();
  friend void protobuf_ShutdownFile_protobuf_2fdata_2eproto();

  void InitAsDefaultInstance();
  static DataRegistration* default_instance_;
};
// -------------------------------------------------------------------

class DataLabel : public ::google::protobuf::Message {
 public:
  DataLabel();
  virtual ~DataLabel();

  DataLabel(const DataLabel& from);

  inline DataLabel& operator=(const DataLabel& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DataLabel& default_instance();

  void Swap(DataLabel* other);

  // implements Message ----------------------------------------------

  DataLabel* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DataLabel& from);
  void MergeFrom(const DataLabel& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 handle = 1;
  inline bool has_handle() const;
  inline void clear_handle();
  static const int kHandleFieldNumber = 1;
  inline ::google::protobuf::uint32 handle() const;
  inline void set_handle(::google::protobuf::uint32 value);

  // optional uint32 value = 2;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 2;
  inline ::google::protobuf::uint32 value() const;
  inline void set_value(::google::protobuf::uint32 value);

  // optional string field_name = 3;
  inline bool has_field_name() const;
  inline void clear_field_name();
  static const int kFieldNameFieldNumber = 3;
  inline const ::std::string& field_name() const;
  inline void set_field_name(const ::std::string& value);
  inline void set_field_name(const char* value);
  inline void set_field_name(const char* value, size_t size);
  inline ::std::string* mutable_field_name();
  inline ::std::string* release_field_name();
  inline void set_allocated_field_name(::std::string* field_name);

  // @@protoc_insertion_point(class_scope:DataLabel)
 private:
  inline void set_has_handle();
  inline void clear_has_handle();
  inline void set_has_value();
  inline void clear_has_value();
  inline void set_has_field_name();
  inline void clear_has_field_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 handle_;
  ::google::protobuf::uint32 value_;
  ::std::string* field_name_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_protobuf_2fdata_2eproto();
  friend void protobuf_AssignDesc_protobuf_2fdata_2eproto();
  friend void protobuf_ShutdownFile_protobuf_2fdata_2eproto();

  void InitAsDefaultInstance();
  static DataLabel* default_instance_;
};
// -------------------------------------------------------------------

class Packet : public ::google::protobuf::Message {
 public:
  Packet();
  virtual ~Packet();

  Packet(const Packet& from);

  inline Packet& operator=(const Packet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Packet& default_instance();

  void Swap(Packet* other);

  // implements Message ----------------------------------------------

  Packet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Packet& from);
  void MergeFrom(const Packet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Data data = 1;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 1;
  inline const ::Data& data() const;
  inline ::Data* mutable_data();
  inline ::Data* release_data();
  inline void set_allocated_data(::Data* data);

  // repeated .DataRegistration data_registrations = 2;
  inline int data_registrations_size() const;
  inline void clear_data_registrations();
  static const int kDataRegistrationsFieldNumber = 2;
  inline const ::DataRegistration& data_registrations(int index) const;
  inline ::DataRegistration* mutable_data_registrations(int index);
  inline ::DataRegistration* add_data_registrations();
  inline const ::google::protobuf::RepeatedPtrField< ::DataRegistration >&
      data_registrations() const;
  inline ::google::protobuf::RepeatedPtrField< ::DataRegistration >*
      mutable_data_registrations();

  // repeated .DataLabel data_labels = 3;
  inline int data_labels_size() const;
  inline void clear_data_labels();
  static const int kDataLabelsFieldNumber = 3;
  inline const ::DataLabel& data_labels(int index) const;
  inline ::DataLabel* mutable_data_labels(int index);
  inline ::DataLabel* add_data_labels();
  inline const ::google::protobuf::RepeatedPtrField< ::DataLabel >&
      data_labels() const;
  inline ::google::protobuf::RepeatedPtrField< ::DataLabel >*
      mutable_data_labels();

  // optional string console_output = 4;
  inline bool has_console_output() const;
  inline void clear_console_output();
  static const int kConsoleOutputFieldNumber = 4;
  inline const ::std::string& console_output() const;
  inline void set_console_output(const ::std::string& value);
  inline void set_console_output(const char* value);
  inline void set_console_output(const char* value, size_t size);
  inline ::std::string* mutable_console_output();
  inline ::std::string* release_console_output();
  inline void set_allocated_console_output(::std::string* console_output);

  // optional string status = 5;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 5;
  inline const ::std::string& status() const;
  inline void set_status(const ::std::string& value);
  inline void set_status(const char* value);
  inline void set_status(const char* value, size_t size);
  inline ::std::string* mutable_status();
  inline ::std::string* release_status();
  inline void set_allocated_status(::std::string* status);

  // @@protoc_insertion_point(class_scope:Packet)
 private:
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_console_output();
  inline void clear_has_console_output();
  inline void set_has_status();
  inline void clear_has_status();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::Data* data_;
  ::google::protobuf::RepeatedPtrField< ::DataRegistration > data_registrations_;
  ::google::protobuf::RepeatedPtrField< ::DataLabel > data_labels_;
  ::std::string* console_output_;
  ::std::string* status_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_protobuf_2fdata_2eproto();
  friend void protobuf_AssignDesc_protobuf_2fdata_2eproto();
  friend void protobuf_ShutdownFile_protobuf_2fdata_2eproto();

  void InitAsDefaultInstance();
  static Packet* default_instance_;
};
// ===================================================================


// ===================================================================

// Data

// optional uint32 handle = 1;
inline bool Data::has_handle() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Data::set_has_handle() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Data::clear_has_handle() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Data::clear_handle() {
  handle_ = 0u;
  clear_has_handle();
}
inline ::google::protobuf::uint32 Data::handle() const {
  return handle_;
}
inline void Data::set_handle(::google::protobuf::uint32 value) {
  set_has_handle();
  handle_ = value;
}

// optional uint32 data_int = 3;
inline bool Data::has_data_int() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Data::set_has_data_int() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Data::clear_has_data_int() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Data::clear_data_int() {
  data_int_ = 0u;
  clear_has_data_int();
}
inline ::google::protobuf::uint32 Data::data_int() const {
  return data_int_;
}
inline void Data::set_data_int(::google::protobuf::uint32 value) {
  set_has_data_int();
  data_int_ = value;
}

// optional float data_float = 4;
inline bool Data::has_data_float() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Data::set_has_data_float() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Data::clear_has_data_float() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Data::clear_data_float() {
  data_float_ = 0;
  clear_has_data_float();
}
inline float Data::data_float() const {
  return data_float_;
}
inline void Data::set_data_float(float value) {
  set_has_data_float();
  data_float_ = value;
}

// optional float data_float_x = 5;
inline bool Data::has_data_float_x() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Data::set_has_data_float_x() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Data::clear_has_data_float_x() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Data::clear_data_float_x() {
  data_float_x_ = 0;
  clear_has_data_float_x();
}
inline float Data::data_float_x() const {
  return data_float_x_;
}
inline void Data::set_data_float_x(float value) {
  set_has_data_float_x();
  data_float_x_ = value;
}

// optional float data_float_y = 6;
inline bool Data::has_data_float_y() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Data::set_has_data_float_y() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Data::clear_has_data_float_y() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Data::clear_data_float_y() {
  data_float_y_ = 0;
  clear_has_data_float_y();
}
inline float Data::data_float_y() const {
  return data_float_y_;
}
inline void Data::set_data_float_y(float value) {
  set_has_data_float_y();
  data_float_y_ = value;
}

// optional float data_float_z = 7;
inline bool Data::has_data_float_z() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Data::set_has_data_float_z() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Data::clear_has_data_float_z() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Data::clear_data_float_z() {
  data_float_z_ = 0;
  clear_has_data_float_z();
}
inline float Data::data_float_z() const {
  return data_float_z_;
}
inline void Data::set_data_float_z(float value) {
  set_has_data_float_z();
  data_float_z_ = value;
}

// optional double time = 8;
inline bool Data::has_time() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Data::set_has_time() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Data::clear_has_time() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Data::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline double Data::time() const {
  return time_;
}
inline void Data::set_time(double value) {
  set_has_time();
  time_ = value;
}

// -------------------------------------------------------------------

// DataRegistration

// optional string field_name = 1;
inline bool DataRegistration::has_field_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DataRegistration::set_has_field_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DataRegistration::clear_has_field_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DataRegistration::clear_field_name() {
  if (field_name_ != &::google::protobuf::internal::kEmptyString) {
    field_name_->clear();
  }
  clear_has_field_name();
}
inline const ::std::string& DataRegistration::field_name() const {
  return *field_name_;
}
inline void DataRegistration::set_field_name(const ::std::string& value) {
  set_has_field_name();
  if (field_name_ == &::google::protobuf::internal::kEmptyString) {
    field_name_ = new ::std::string;
  }
  field_name_->assign(value);
}
inline void DataRegistration::set_field_name(const char* value) {
  set_has_field_name();
  if (field_name_ == &::google::protobuf::internal::kEmptyString) {
    field_name_ = new ::std::string;
  }
  field_name_->assign(value);
}
inline void DataRegistration::set_field_name(const char* value, size_t size) {
  set_has_field_name();
  if (field_name_ == &::google::protobuf::internal::kEmptyString) {
    field_name_ = new ::std::string;
  }
  field_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* DataRegistration::mutable_field_name() {
  set_has_field_name();
  if (field_name_ == &::google::protobuf::internal::kEmptyString) {
    field_name_ = new ::std::string;
  }
  return field_name_;
}
inline ::std::string* DataRegistration::release_field_name() {
  clear_has_field_name();
  if (field_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = field_name_;
    field_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void DataRegistration::set_allocated_field_name(::std::string* field_name) {
  if (field_name_ != &::google::protobuf::internal::kEmptyString) {
    delete field_name_;
  }
  if (field_name) {
    set_has_field_name();
    field_name_ = field_name;
  } else {
    clear_has_field_name();
    field_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .vb_data_type_t type = 2;
inline bool DataRegistration::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DataRegistration::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DataRegistration::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DataRegistration::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::vb_data_type_t DataRegistration::type() const {
  return static_cast< ::vb_data_type_t >(type_);
}
inline void DataRegistration::set_type(::vb_data_type_t value) {
  assert(::vb_data_type_t_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional uint32 handle = 3;
inline bool DataRegistration::has_handle() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DataRegistration::set_has_handle() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DataRegistration::clear_has_handle() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DataRegistration::clear_handle() {
  handle_ = 0u;
  clear_has_handle();
}
inline ::google::protobuf::uint32 DataRegistration::handle() const {
  return handle_;
}
inline void DataRegistration::set_handle(::google::protobuf::uint32 value) {
  set_has_handle();
  handle_ = value;
}

// optional float range_min = 4;
inline bool DataRegistration::has_range_min() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void DataRegistration::set_has_range_min() {
  _has_bits_[0] |= 0x00000008u;
}
inline void DataRegistration::clear_has_range_min() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void DataRegistration::clear_range_min() {
  range_min_ = 0;
  clear_has_range_min();
}
inline float DataRegistration::range_min() const {
  return range_min_;
}
inline void DataRegistration::set_range_min(float value) {
  set_has_range_min();
  range_min_ = value;
}

// optional float range_max = 5;
inline bool DataRegistration::has_range_max() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void DataRegistration::set_has_range_max() {
  _has_bits_[0] |= 0x00000010u;
}
inline void DataRegistration::clear_has_range_max() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void DataRegistration::clear_range_max() {
  range_max_ = 0;
  clear_has_range_max();
}
inline float DataRegistration::range_max() const {
  return range_max_;
}
inline void DataRegistration::set_range_max(float value) {
  set_has_range_max();
  range_max_ = value;
}

// -------------------------------------------------------------------

// DataLabel

// optional uint32 handle = 1;
inline bool DataLabel::has_handle() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DataLabel::set_has_handle() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DataLabel::clear_has_handle() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DataLabel::clear_handle() {
  handle_ = 0u;
  clear_has_handle();
}
inline ::google::protobuf::uint32 DataLabel::handle() const {
  return handle_;
}
inline void DataLabel::set_handle(::google::protobuf::uint32 value) {
  set_has_handle();
  handle_ = value;
}

// optional uint32 value = 2;
inline bool DataLabel::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DataLabel::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DataLabel::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DataLabel::clear_value() {
  value_ = 0u;
  clear_has_value();
}
inline ::google::protobuf::uint32 DataLabel::value() const {
  return value_;
}
inline void DataLabel::set_value(::google::protobuf::uint32 value) {
  set_has_value();
  value_ = value;
}

// optional string field_name = 3;
inline bool DataLabel::has_field_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DataLabel::set_has_field_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DataLabel::clear_has_field_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DataLabel::clear_field_name() {
  if (field_name_ != &::google::protobuf::internal::kEmptyString) {
    field_name_->clear();
  }
  clear_has_field_name();
}
inline const ::std::string& DataLabel::field_name() const {
  return *field_name_;
}
inline void DataLabel::set_field_name(const ::std::string& value) {
  set_has_field_name();
  if (field_name_ == &::google::protobuf::internal::kEmptyString) {
    field_name_ = new ::std::string;
  }
  field_name_->assign(value);
}
inline void DataLabel::set_field_name(const char* value) {
  set_has_field_name();
  if (field_name_ == &::google::protobuf::internal::kEmptyString) {
    field_name_ = new ::std::string;
  }
  field_name_->assign(value);
}
inline void DataLabel::set_field_name(const char* value, size_t size) {
  set_has_field_name();
  if (field_name_ == &::google::protobuf::internal::kEmptyString) {
    field_name_ = new ::std::string;
  }
  field_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* DataLabel::mutable_field_name() {
  set_has_field_name();
  if (field_name_ == &::google::protobuf::internal::kEmptyString) {
    field_name_ = new ::std::string;
  }
  return field_name_;
}
inline ::std::string* DataLabel::release_field_name() {
  clear_has_field_name();
  if (field_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = field_name_;
    field_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void DataLabel::set_allocated_field_name(::std::string* field_name) {
  if (field_name_ != &::google::protobuf::internal::kEmptyString) {
    delete field_name_;
  }
  if (field_name) {
    set_has_field_name();
    field_name_ = field_name;
  } else {
    clear_has_field_name();
    field_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// Packet

// optional .Data data = 1;
inline bool Packet::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Packet::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Packet::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Packet::clear_data() {
  if (data_ != NULL) data_->::Data::Clear();
  clear_has_data();
}
inline const ::Data& Packet::data() const {
  return data_ != NULL ? *data_ : *default_instance_->data_;
}
inline ::Data* Packet::mutable_data() {
  set_has_data();
  if (data_ == NULL) data_ = new ::Data;
  return data_;
}
inline ::Data* Packet::release_data() {
  clear_has_data();
  ::Data* temp = data_;
  data_ = NULL;
  return temp;
}
inline void Packet::set_allocated_data(::Data* data) {
  delete data_;
  data_ = data;
  if (data) {
    set_has_data();
  } else {
    clear_has_data();
  }
}

// repeated .DataRegistration data_registrations = 2;
inline int Packet::data_registrations_size() const {
  return data_registrations_.size();
}
inline void Packet::clear_data_registrations() {
  data_registrations_.Clear();
}
inline const ::DataRegistration& Packet::data_registrations(int index) const {
  return data_registrations_.Get(index);
}
inline ::DataRegistration* Packet::mutable_data_registrations(int index) {
  return data_registrations_.Mutable(index);
}
inline ::DataRegistration* Packet::add_data_registrations() {
  return data_registrations_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::DataRegistration >&
Packet::data_registrations() const {
  return data_registrations_;
}
inline ::google::protobuf::RepeatedPtrField< ::DataRegistration >*
Packet::mutable_data_registrations() {
  return &data_registrations_;
}

// repeated .DataLabel data_labels = 3;
inline int Packet::data_labels_size() const {
  return data_labels_.size();
}
inline void Packet::clear_data_labels() {
  data_labels_.Clear();
}
inline const ::DataLabel& Packet::data_labels(int index) const {
  return data_labels_.Get(index);
}
inline ::DataLabel* Packet::mutable_data_labels(int index) {
  return data_labels_.Mutable(index);
}
inline ::DataLabel* Packet::add_data_labels() {
  return data_labels_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::DataLabel >&
Packet::data_labels() const {
  return data_labels_;
}
inline ::google::protobuf::RepeatedPtrField< ::DataLabel >*
Packet::mutable_data_labels() {
  return &data_labels_;
}

// optional string console_output = 4;
inline bool Packet::has_console_output() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Packet::set_has_console_output() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Packet::clear_has_console_output() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Packet::clear_console_output() {
  if (console_output_ != &::google::protobuf::internal::kEmptyString) {
    console_output_->clear();
  }
  clear_has_console_output();
}
inline const ::std::string& Packet::console_output() const {
  return *console_output_;
}
inline void Packet::set_console_output(const ::std::string& value) {
  set_has_console_output();
  if (console_output_ == &::google::protobuf::internal::kEmptyString) {
    console_output_ = new ::std::string;
  }
  console_output_->assign(value);
}
inline void Packet::set_console_output(const char* value) {
  set_has_console_output();
  if (console_output_ == &::google::protobuf::internal::kEmptyString) {
    console_output_ = new ::std::string;
  }
  console_output_->assign(value);
}
inline void Packet::set_console_output(const char* value, size_t size) {
  set_has_console_output();
  if (console_output_ == &::google::protobuf::internal::kEmptyString) {
    console_output_ = new ::std::string;
  }
  console_output_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Packet::mutable_console_output() {
  set_has_console_output();
  if (console_output_ == &::google::protobuf::internal::kEmptyString) {
    console_output_ = new ::std::string;
  }
  return console_output_;
}
inline ::std::string* Packet::release_console_output() {
  clear_has_console_output();
  if (console_output_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = console_output_;
    console_output_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Packet::set_allocated_console_output(::std::string* console_output) {
  if (console_output_ != &::google::protobuf::internal::kEmptyString) {
    delete console_output_;
  }
  if (console_output) {
    set_has_console_output();
    console_output_ = console_output;
  } else {
    clear_has_console_output();
    console_output_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string status = 5;
inline bool Packet::has_status() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Packet::set_has_status() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Packet::clear_has_status() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Packet::clear_status() {
  if (status_ != &::google::protobuf::internal::kEmptyString) {
    status_->clear();
  }
  clear_has_status();
}
inline const ::std::string& Packet::status() const {
  return *status_;
}
inline void Packet::set_status(const ::std::string& value) {
  set_has_status();
  if (status_ == &::google::protobuf::internal::kEmptyString) {
    status_ = new ::std::string;
  }
  status_->assign(value);
}
inline void Packet::set_status(const char* value) {
  set_has_status();
  if (status_ == &::google::protobuf::internal::kEmptyString) {
    status_ = new ::std::string;
  }
  status_->assign(value);
}
inline void Packet::set_status(const char* value, size_t size) {
  set_has_status();
  if (status_ == &::google::protobuf::internal::kEmptyString) {
    status_ = new ::std::string;
  }
  status_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Packet::mutable_status() {
  set_has_status();
  if (status_ == &::google::protobuf::internal::kEmptyString) {
    status_ = new ::std::string;
  }
  return status_;
}
inline ::std::string* Packet::release_status() {
  clear_has_status();
  if (status_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = status_;
    status_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Packet::set_allocated_status(::std::string* status) {
  if (status_ != &::google::protobuf::internal::kEmptyString) {
    delete status_;
  }
  if (status) {
    set_has_status();
    status_ = status;
  } else {
    clear_has_status();
    status_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::vb_data_type_t>() {
  return ::vb_data_type_t_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protobuf_2fdata_2eproto__INCLUDED
